name: Gatsby Publish

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: henrysha/gatsby-gh-pages-action@2.2.1
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: main
          pkg-manager: pnpm
